---

- name: Install and configure Vault
  hosts: default
  become: true

  tasks:
    - name: Apt update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Apt upgrade
      ansible.builtin.apt:
        upgrade: dist
    - name: Add hashicorp key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/trusted.gpg.d/hashicorp.asc
        mode: 0644
        force: true
    - name: Add hashicorp source
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc] https://apt.releases.hashicorp.com jammy main
        state: present
    - name: Install Vault
      ansible.builtin.apt:
        name: vault
        state: present
        update_cache: true
    - name: Add vault configuration
      ansible.builtin.template:
        src: vault.hcl
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: 0644
